(source "jcs-elpa")
(source "melpa")

(package "meta-view" "0.1.0" "View metadata from .NET assemblies")
(package-file "meta-view.el")

(depends-on "emacs" "26.1")
(depends-on "csharp-mode")
(depends-on "meta-net")
(depends-on "ht")
(depends-on "f")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
